import { Host_Grotesk } from "next/font/google";
import Provider from "./provider";
import "./globals.css";

const host_GroteskSans = Host_Grotesk({
  subsets: ["latin"],
  variable: "--font-host-grotesk-sans",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={host_GroteskSans.className}
      >
        <Provider>
         {children}
        </Provider>
        
      </body>
    </html>
  );
}
